INSERT INTO categories (name, description) VALUES
('Fiction', 'Fictional books including novels, short stories, and dramas'),
('Non-Fiction', 'Non-Fictional books covering real-life events, biographies, and factual content'),
('Science', 'Science related books including physics, chemistry, biology, and more'),
('History', 'Historical books covering ancient, medieval, and modern history'),
('Fantasy', 'Books with magical and supernatural elements'),
('Mystery', 'Books involving suspense, crime, and detective stories'),
('Romance', 'Books focusing on romantic relationships'),
('Thriller', 'Books filled with excitement, suspense, and high stakes'),
('Biography', 'Books about the lives of real people'),
('Self-Help', 'Books aimed at personal improvement and growth'),
('Health & Wellness', 'Books about physical and mental health, fitness, and wellbeing'),
('Technology', 'Books covering technological advancements, programming, and gadgets'),
('Travel', 'Books about travel experiences, guides, and adventures'),
('Art & Photography', 'Books showcasing artistic works and photography techniques'),
('Cooking', 'Cookbooks and books about culinary arts'),
('Philosophy', 'Books discussing philosophical theories and thinkers'),
('Religion', 'Books about religious beliefs, practices, and history'),
('Children', 'Books for young readers, including picture books and early readers'),
('Young Adult', 'Books aimed at teenagers and young adults'),
('Poetry', 'Collections of poems and verses'),
('Drama', 'Books focused on dramatic literature and plays'),
('Horror', 'Books intended to scare and thrill the reader'),
('Comics & Graphic Novels', 'Books in comic or graphic novel format'),
('Education', 'Books related to teaching and learning processes'),
('Science Fiction', 'Books exploring futuristic concepts, space, and technology'),
('Adventure', 'Books filled with exciting journeys and explorations'),
('Classics', 'Books that have stood the test of time and are considered literary masterpieces'),
('Economics', 'Books about economic theories, practices, and history'),
('Politics', 'Books discussing political theories, systems, and figures'),
('Memoir', 'Books where the author recounts personal experiences'),
('Spirituality', 'Books exploring spiritual beliefs and practices'),
('Sports', 'Books about various sports, athletes, and sporting events'),
('Humor', 'Books intended to entertain and make the reader laugh'),
('Environmental', 'Books focused on environmental issues and nature'),
('Music', 'Books about music theory, history, and musicians'),
('Business', 'Books covering business strategies, entrepreneurship, and management');
